# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dk5HD-bAmsR4hHtyOuikfyJaYECrwrW
"""

!pip install streamlit pyngrok -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# # ---- Your Recipe Database ----
# recipes = [
#     {"name": "Tomato Toast", "ingredients": ["bread", "tomato", "butter", "salt"]},
#     {"name": "Egg Fried Rice", "ingredients": ["rice", "egg", "onion", "soy sauce", "oil"]},
#     {"name": "Banana Smoothie", "ingredients": ["banana", "milk", "sugar", "ice"]},
#     {"name": "Vegetable Soup", "ingredients": ["potato", "carrot", "tomato", "onion", "water", "salt"]},
#     {"name": "Cheese Sandwich", "ingredients": ["bread", "cheese", "butter", "tomato"]},
#     {"name": "Pasta with Tomato", "ingredients": ["pasta", "tomato", "garlic", "oil", "salt"]},
#     {"name": "Omelette", "ingredients": ["egg", "onion", "tomato", "oil", "salt"]},
#     {"name": "Paneer Butter Masala", "ingredients": ["paneer", "tomato", "onion", "butter", "cream"]},
#     {"name": "Dal Tadka", "ingredients": ["lentils", "tomato", "onion", "garlic", "cumin", "oil"]},
#     {"name": "Aloo Sabzi", "ingredients": ["potato", "tomato", "onion", "oil"]},
#     {"name": "Mango Lassi", "ingredients": ["mango", "yogurt", "sugar", "milk"]},
#     {"name": "Poha", "ingredients": ["flattened rice", "onion", "potato", "oil"]},
#     {"name": "Upma", "ingredients": ["semolina", "onion", "tomato", "oil"]},
#     {"name": "Bread Upma", "ingredients": ["bread", "onion", "tomato", "oil"]},
#     {"name": "Maggi Noodles", "ingredients": ["noodles", "onion", "tomato", "egg", "oil"]},
#     {"name": "Curd Rice", "ingredients": ["rice", "yogurt", "salt", "mustard seeds"]},
#     {"name": "Avocado Toast", "ingredients": ["bread", "avocado", "lemon", "salt"]},
#     {"name": "French Toast", "ingredients": ["bread", "egg", "milk", "sugar", "butter"]},
#     {"name": "Vegetable Pulao", "ingredients": ["rice", "carrot", "peas", "onion", "oil"]},
#     {"name": "Peanut Butter Toast", "ingredients": ["bread", "peanut butter", "banana"]},
#     {"name": "Tomato Oats", "ingredients": ["oats", "tomato", "onion", "salt", "oil"]},
#     {"name": "Chana Masala", "ingredients": ["chickpeas", "tomato", "onion", "garlic"]},
#     {"name": "Khichdi", "ingredients": ["rice", "lentils", "turmeric", "ghee", "salt"]},
#     {"name": "Pancakes", "ingredients": ["flour", "egg", "milk", "sugar", "butter"]},
#     {"name": "Lemon Rice", "ingredients": ["rice", "lemon", "mustard seeds", "oil", "salt"]},
# ]
# 
# # ---- AI Matching Function ----
# def suggest_recipes(user_ingredients):
#     user_ing = [i.strip().lower() for i in user_ingredients.split(",")]
#     results = []
#     for recipe in recipes:
#         matched = [i for i in recipe["ingredients"] if i in user_ing]
#         score = len(matched) / len(recipe["ingredients"])
#         if score > 0:
#             results.append({"name": recipe["name"], "score": score,
#                             "matched": matched, "total": len(recipe["ingredients"])})
#     results.sort(key=lambda x: x["score"], reverse=True)
#     return results[:5]
# 
# # ---- Streamlit App UI ----
# st.set_page_config(page_title="AI Recipe Suggester", page_icon="🍽️")
# st.title("🍽️ AI Recipe Suggester")
# st.write("Type the ingredients you have, and I'll suggest recipes!")
# 
# user_input = st.text_input("Enter ingredients (comma separated):",
#                             placeholder="e.g. egg, tomato, bread, onion")
# 
# if st.button("Suggest Recipes"):
#     if user_input:
#         suggestions = suggest_recipes(user_input)
#         if suggestions:
#             st.success(f"Found {len(suggestions)} recipes for you!")
#             for r in suggestions:
#                 pct = int(r['score'] * 100)
#                 st.subheader(f"🍴 {r['name']} — {pct}% match")
#                 st.write(f"You have **{len(r['matched'])}** of **{r['total']}** ingredients")
#                 st.write(f"Matched: {', '.join(r['matched'])}")
#                 st.progress(r['score'])
#                 st.divider()
#         else:
#             st.warning("No recipes found. Try different ingredients!")
#     else:
#         st.error("Please enter some ingredients first!")